# This is a basic workflow to help you get started with Actions

name: CI/CD Airflow PT GUE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: 'Update Cloud Storage Airflow'
    permissions:
      contents: 'read'
      id-token: 'write'

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Auth'
        uses: 'google-github-actions/auth@v0.7.3'
        with:
          workload_identity_provider: 'projects/1085580725380/locations/global/workloadIdentityPools/github-action-pool/providers/github-provider'
          service_account: 'gue-airflow-github-action@gue-analytics-315803.iam.gserviceaccount.com'

      - id: 'update-folder-data'
        name: 'Update Folder Data'
        uses: 'google-github-actions/upload-cloud-storage@v0.10.2'
        with:
          path: '/home/runner/work/gue_airflow/gue_airflow/data'
          destination: 'asia-southeast1-airflow-c8bbb248-bucket'

      - id: 'update-folder-dags'
        name: 'Update Folder Dags'
        uses: 'google-github-actions/upload-cloud-storage@v0.10.2'
        with:
          path: '/home/runner/work/gue_airflow/gue_airflow/dags'
          destination: 'asia-southeast1-airflow-c8bbb248-bucket'
